/*
RECORD CLASSES :
    - A record class is a special kind of class introduced in Java 14.
    - Its primary purpose is to act as a transparent carrier for immutable data.
    - They automatically generate common boilerplate code, such as constructors, getters, setters, and the toString(), hashCode(), and equals() methods.
 */

package AdvanceJava;
import java.util.*;

record Person(String name, int age) {                                   // Creating a Record Person that auto generates several methods

    public Person(String name, int age) {                               // Constructor
        this.name = name;
        this.age = age;
    }
}

public class RecordClasses {
    public static void main(String[] args) {

        Person person1 = new Person("John", 30);
        Person person2 = new Person("Charles", 25);

        System.out.println(person1);                                        // Output: Person[name=Alice, age=30]
        System.out.println(person2);                                        // Output: Person[name=Bob, age=25]

        System.out.println("Name of person1: " + person1.name());           // Using getters (Auto-generated by record class)
        System.out.println("Age of person2: " + person2.age());

        System.out.println("Are person1 and person2 equal? " + person1.equals(person2));    // Checking equality - False (Auto-generated by record class)

        System.out.println("Hash codes of both persons : " + person1.hashCode() + " " +person2.hashCode());       // Hash codes (Auto-generated by record class)

    }
}
